// <auto-generated />
using System;
using GigsNearMe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GigsNearMe.Migrations
{
    [DbContext(typeof(GigsNearMeDbContext))]
    partial class GigsNearMeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GigsNearMe.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistID = 1,
                            Name = "The Marillos"
                        },
                        new
                        {
                            ArtistID = 2,
                            Name = "Fishmeister"
                        },
                        new
                        {
                            ArtistID = 3,
                            Name = "Pale Red"
                        },
                        new
                        {
                            ArtistID = 4,
                            Name = "Fender Dude"
                        },
                        new
                        {
                            ArtistID = 5,
                            Name = "Slightly Fuming"
                        },
                        new
                        {
                            ArtistID = 6,
                            Name = "Chunky Rain Storm"
                        },
                        new
                        {
                            ArtistID = 7,
                            Name = "Electrifying"
                        },
                        new
                        {
                            ArtistID = 8,
                            Name = "DepartingArtist"
                        },
                        new
                        {
                            ArtistID = 9,
                            Name = "BouncyArtist"
                        });
                });

            modelBuilder.Entity("GigsNearMe.Models.Gig", b =>
                {
                    b.Property<int>("GigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("GigID");

                    b.HasIndex("ArtistID");

                    b.HasIndex("TourID");

                    b.HasIndex("VenueID");

                    b.ToTable("Gigs");

                    b.HasData(
                        new
                        {
                            GigID = 1,
                            ArtistID = 1,
                            Date = new DateTime(2021, 7, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 1,
                            VenueID = 17
                        },
                        new
                        {
                            GigID = 2,
                            ArtistID = 1,
                            Date = new DateTime(2021, 7, 24, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 1,
                            VenueID = 18
                        },
                        new
                        {
                            GigID = 3,
                            ArtistID = 1,
                            Date = new DateTime(2021, 7, 28, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 1,
                            VenueID = 19
                        },
                        new
                        {
                            GigID = 4,
                            ArtistID = 1,
                            Date = new DateTime(2021, 8, 1, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 1,
                            VenueID = 20
                        },
                        new
                        {
                            GigID = 5,
                            ArtistID = 1,
                            Date = new DateTime(2021, 8, 12, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 1,
                            VenueID = 16
                        },
                        new
                        {
                            GigID = 6,
                            ArtistID = 1,
                            Date = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 2,
                            VenueID = 1
                        },
                        new
                        {
                            GigID = 7,
                            ArtistID = 1,
                            Date = new DateTime(2021, 11, 25, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 2,
                            VenueID = 2
                        },
                        new
                        {
                            GigID = 8,
                            ArtistID = 1,
                            Date = new DateTime(2021, 11, 27, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 2,
                            VenueID = 3
                        },
                        new
                        {
                            GigID = 9,
                            ArtistID = 1,
                            Date = new DateTime(2021, 11, 29, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 2,
                            VenueID = 4
                        },
                        new
                        {
                            GigID = 10,
                            ArtistID = 2,
                            Date = new DateTime(2021, 8, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 3,
                            VenueID = 5
                        },
                        new
                        {
                            GigID = 11,
                            ArtistID = 2,
                            Date = new DateTime(2021, 8, 24, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 3,
                            VenueID = 6
                        },
                        new
                        {
                            GigID = 12,
                            ArtistID = 2,
                            Date = new DateTime(2021, 8, 26, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 3,
                            VenueID = 7
                        },
                        new
                        {
                            GigID = 13,
                            ArtistID = 2,
                            Date = new DateTime(2021, 8, 28, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 3,
                            VenueID = 8
                        },
                        new
                        {
                            GigID = 14,
                            ArtistID = 2,
                            Date = new DateTime(2021, 8, 30, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 3,
                            VenueID = 9
                        },
                        new
                        {
                            GigID = 15,
                            ArtistID = 2,
                            Date = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 4,
                            VenueID = 4
                        },
                        new
                        {
                            GigID = 16,
                            ArtistID = 5,
                            Date = new DateTime(2021, 10, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 5,
                            VenueID = 13
                        },
                        new
                        {
                            GigID = 17,
                            ArtistID = 7,
                            Date = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 4
                        },
                        new
                        {
                            GigID = 18,
                            ArtistID = 7,
                            Date = new DateTime(2021, 11, 29, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 6
                        },
                        new
                        {
                            GigID = 19,
                            ArtistID = 7,
                            Date = new DateTime(2021, 12, 1, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 7
                        },
                        new
                        {
                            GigID = 20,
                            ArtistID = 7,
                            Date = new DateTime(2021, 12, 8, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 8
                        },
                        new
                        {
                            GigID = 21,
                            ArtistID = 7,
                            Date = new DateTime(2021, 12, 13, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 10
                        },
                        new
                        {
                            GigID = 22,
                            ArtistID = 7,
                            Date = new DateTime(2021, 12, 18, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 6,
                            VenueID = 11
                        },
                        new
                        {
                            GigID = 23,
                            ArtistID = 8,
                            Date = new DateTime(2021, 6, 30, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 7,
                            VenueID = 24
                        },
                        new
                        {
                            GigID = 24,
                            ArtistID = 8,
                            Date = new DateTime(2021, 7, 2, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 7,
                            VenueID = 25
                        },
                        new
                        {
                            GigID = 25,
                            ArtistID = 8,
                            Date = new DateTime(2021, 7, 4, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 7,
                            VenueID = 26
                        },
                        new
                        {
                            GigID = 26,
                            ArtistID = 8,
                            Date = new DateTime(2021, 8, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 8,
                            VenueID = 16
                        },
                        new
                        {
                            GigID = 27,
                            ArtistID = 8,
                            Date = new DateTime(2021, 9, 1, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 8,
                            VenueID = 18
                        },
                        new
                        {
                            GigID = 28,
                            ArtistID = 8,
                            Date = new DateTime(2021, 9, 3, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 8,
                            VenueID = 22
                        },
                        new
                        {
                            GigID = 29,
                            ArtistID = 9,
                            Date = new DateTime(2021, 6, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 9,
                            VenueID = 24
                        },
                        new
                        {
                            GigID = 30,
                            ArtistID = 9,
                            Date = new DateTime(2021, 7, 3, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 9,
                            VenueID = 25
                        },
                        new
                        {
                            GigID = 31,
                            ArtistID = 9,
                            Date = new DateTime(2021, 7, 5, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716),
                            TourID = 9,
                            VenueID = 26
                        });
                });

            modelBuilder.Entity("GigsNearMe.Models.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("TourID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourID = 1,
                            ArtistID = 1,
                            Name = "North American",
                            Start = new DateTime(2021, 7, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 2,
                            ArtistID = 1,
                            Name = "European",
                            Start = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 3,
                            ArtistID = 2,
                            Name = "European",
                            Start = new DateTime(2021, 8, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 4,
                            ArtistID = 2,
                            Name = "One and Done",
                            Start = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 5,
                            ArtistID = 5,
                            Name = "One Night Only",
                            Start = new DateTime(2021, 10, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 6,
                            ArtistID = 7,
                            Name = "Down Under Gone Topside",
                            Start = new DateTime(2021, 11, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 7,
                            ArtistID = 8,
                            Name = "Me Without Them",
                            Start = new DateTime(2021, 6, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 8,
                            ArtistID = 8,
                            Name = "Not Missing Them",
                            Start = new DateTime(2021, 8, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        },
                        new
                        {
                            TourID = 9,
                            ArtistID = 9,
                            Name = "Following Them",
                            Start = new DateTime(2021, 6, 23, 22, 38, 18, 245, DateTimeKind.Utc).AddTicks(8716)
                        });
                });

            modelBuilder.Entity("GigsNearMe.Models.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrCounty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueID");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueID = 1,
                            City = "Belfast",
                            Country = 6,
                            Name = "A Hall in Ulster",
                            StateOrCounty = "County Antrim"
                        },
                        new
                        {
                            VenueID = 2,
                            City = "Dublin",
                            Country = 5,
                            Name = "Vicarage Street",
                            StateOrCounty = "County Dublin"
                        },
                        new
                        {
                            VenueID = 3,
                            City = "Gateshead",
                            Country = 2,
                            Name = "The Sage Plant",
                            StateOrCounty = "Tyne and Wear"
                        },
                        new
                        {
                            VenueID = 4,
                            City = "Cambridge",
                            Country = 2,
                            Name = "A Corn Exchange",
                            StateOrCounty = "Cambridgeshire"
                        },
                        new
                        {
                            VenueID = 5,
                            City = "Birmingham",
                            Country = 2,
                            Name = "Large Symphony Hall",
                            StateOrCounty = "West Midlands"
                        },
                        new
                        {
                            VenueID = 6,
                            City = "Brighton",
                            Country = 2,
                            Name = "The Shiny Dome",
                            StateOrCounty = "Sussex"
                        },
                        new
                        {
                            VenueID = 7,
                            City = "Reading",
                            Country = 2,
                            Name = "A Six-Sider",
                            StateOrCounty = "Berkshire"
                        },
                        new
                        {
                            VenueID = 8,
                            City = "Glasgow",
                            Country = 8,
                            Name = "Oran Mor or Less",
                            StateOrCounty = "Strathclyde"
                        },
                        new
                        {
                            VenueID = 9,
                            City = "Villersexel",
                            Country = 3,
                            Name = "Chateau de chateau",
                            StateOrCounty = "Haute-Saone"
                        },
                        new
                        {
                            VenueID = 10,
                            City = "Frankfurt",
                            Country = 4,
                            Name = "Thunderthalle",
                            StateOrCounty = "Hesse"
                        },
                        new
                        {
                            VenueID = 11,
                            City = "Essen",
                            Country = 4,
                            Name = "Rounded Colosseum",
                            StateOrCounty = "North Rhine-Westphalia"
                        },
                        new
                        {
                            VenueID = 12,
                            City = "Berlin",
                            Country = 4,
                            Name = "Admiralsbalast",
                            StateOrCounty = "Brandenburg"
                        },
                        new
                        {
                            VenueID = 13,
                            City = "Warsaw",
                            Country = 7,
                            Name = "Progresjaorno",
                            StateOrCounty = "Masovia"
                        },
                        new
                        {
                            VenueID = 14,
                            City = "Tampa",
                            Country = 9,
                            Name = "Boat Trip to the Edge",
                            StateOrCounty = "FL"
                        },
                        new
                        {
                            VenueID = 15,
                            City = "Orlando",
                            Country = 9,
                            Name = "Some Plaza",
                            StateOrCounty = "FL"
                        },
                        new
                        {
                            VenueID = 16,
                            City = "Buffalo",
                            Country = 9,
                            Name = "The Town Ballroom",
                            StateOrCounty = "NY"
                        },
                        new
                        {
                            VenueID = 17,
                            City = "Los Angeles",
                            Country = 9,
                            Name = "A Theater",
                            StateOrCounty = "CA"
                        },
                        new
                        {
                            VenueID = 18,
                            City = "San Francisco",
                            Country = 9,
                            Name = "The Old-time Ballroom",
                            StateOrCounty = "CA"
                        },
                        new
                        {
                            VenueID = 19,
                            City = "Washington",
                            Country = 9,
                            Name = "2:30am Club",
                            StateOrCounty = "DC"
                        },
                        new
                        {
                            VenueID = 20,
                            City = "New York",
                            Country = 9,
                            Name = "PlayMore Theater",
                            StateOrCounty = "NY"
                        },
                        new
                        {
                            VenueID = 21,
                            City = "Quebec",
                            Country = 1,
                            Name = "The Imperial Ball",
                            StateOrCounty = "QC"
                        },
                        new
                        {
                            VenueID = 22,
                            City = "Montreal",
                            Country = 1,
                            Name = "Phone Theatre",
                            StateOrCounty = "QC"
                        },
                        new
                        {
                            VenueID = 23,
                            City = "Toronto",
                            Country = 1,
                            Name = "Our Music Hall",
                            StateOrCounty = "ON"
                        },
                        new
                        {
                            VenueID = 24,
                            City = "Sydney, NSW",
                            Country = 0,
                            Name = "Majestic Opera House",
                            StateOrCounty = "NSW"
                        },
                        new
                        {
                            VenueID = 25,
                            City = "Brisbane",
                            Country = 0,
                            Name = "Triffids",
                            StateOrCounty = "QLD"
                        },
                        new
                        {
                            VenueID = 26,
                            City = "Sydney",
                            Country = 0,
                            Name = "Bank Arena",
                            StateOrCounty = "NSW"
                        });
                });

            modelBuilder.Entity("GigsNearMe.Models.Gig", b =>
                {
                    b.HasOne("GigsNearMe.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GigsNearMe.Models.Tour", "Tour")
                        .WithMany("Gigs")
                        .HasForeignKey("TourID");

                    b.HasOne("GigsNearMe.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Tour");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("GigsNearMe.Models.Tour", b =>
                {
                    b.HasOne("GigsNearMe.Models.Artist", "Artist")
                        .WithMany("Tours")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GigsNearMe.Models.Artist", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("GigsNearMe.Models.Tour", b =>
                {
                    b.Navigation("Gigs");
                });
#pragma warning restore 612, 618
        }
    }
}
